### ISSUE TITLE
vector_rectify_dialog.py", line 314, in getValues   print item.text()

### ISSUE THREAD

**Issue by pyarchinit** [danistrigaro/SpatialAdjustment#6]
Qgis 2.10.0 - Windows 7: under Windows the print command raises an error due to writing permission denied.

Comment the line.

Traceback (most recent call last):
  File "C:/Users/Windows/.qgis2/python/plugins\VectorRectify\vector_rectify.py", line 198, in run
    self.dlg.runAdjust()
  File "C:/Users/Windows/.qgis2/python/plugins\VectorRectify\vector_rectify_dialog.py", line 338, in runAdjust
    data = self.getValues()
  File "C:/Users/Windows/.qgis2/python/plugins\VectorRectify\vector_rectify_dialog.py", line 314, in getValues
    print item.text()
IOError: [Errno 9] Bad file descriptor

**Comment by danistrigaro** [comment]
Ok. I commented the 'print' command.
